# Generated by Django 4.0.4 on 2022-06-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRule',
            fields=[
                ('ID_RU_DS', models.BigAutoField(primary_key=True, serialize=False, verbose_name='DepositRuleID')),
                ('MO_DS', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='DepositAmount')),
                ('LU_UOM_DS_PD', models.CharField(max_length=2, verbose_name='DepositPaidOnUnitOfMeasureCode')),
                ('MO_UOM_DS_PD', models.DecimalField(decimal_places=5, max_digits=16, verbose_name='DepositPaidPerUnitOfMeasureAmount')),
                ('SC_RU_DS', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2, verbose_name='Status Code')),
            ],
            options={
                'db_table': 'RU_DS',
            },
        ),
    ]
