# Generated by Django 4.0.4 on 2022-07-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositrule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrule',
            name='DATE_OF_CREATION',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
