# Generated by Django 4.0.4 on 2022-07-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depositrule', '0002_depositrule_date_of_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositrule',
            name='DATE_OF_CREATION',
        ),
    ]
