# Generated by Django 4.0.4 on 2022-07-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depositrule', '0003_remove_depositrule_date_of_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositrule',
            old_name='SC_RU_DS',
            new_name='Status',
        ),
    ]
