# Generated by Django 4.0.4 on 2022-07-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depositrule', '0004_rename_sc_ru_ds_depositrule_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositrule',
            old_name='MO_DS',
            new_name='deposit_amount',
        ),
        migrations.RenameField(
            model_name='depositrule',
            old_name='MO_UOM_DS_PD',
            new_name='measure_amount',
        ),
        migrations.RenameField(
            model_name='depositrule',
            old_name='LU_UOM_DS_PD',
            new_name='unit_of_measure_code',
        ),
    ]
