# Generated by Django 4.0.4 on 2022-07-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depositrule', '0005_rename_mo_ds_depositrule_deposit_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositrule',
            old_name='unit_of_measure_code',
            new_name='LU_UOM_DS_PD',
        ),
        migrations.RenameField(
            model_name='depositrule',
            old_name='deposit_amount',
            new_name='MO_DS',
        ),
        migrations.RenameField(
            model_name='depositrule',
            old_name='measure_amount',
            new_name='MO_UOM_DS_PD',
        ),
        migrations.RenameField(
            model_name='depositrule',
            old_name='Status',
            new_name='SC_RU_DS',
        ),
    ]
