# Generated by Django 4.0.4 on 2022-07-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unitofmeasure', '0003_unitofmeasure_created_at_unitofmeasure_status_uom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitofmeasure',
            name='CREATED_AT',
        ),
        migrations.RemoveField(
            model_name='unitofmeasure',
            name='STATUS_UOM',
        ),
    ]
