# Generated by Django 4.0.4 on 2022-07-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitofmeasure', '0004_remove_unitofmeasure_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasure',
            name='CREATED_AT',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='UnitOfMeasure Created At'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='STATUS_UOM',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2, verbose_name='UnitOfMeasure Staus'),
        ),
    ]
