# Generated by Django 4.0.4 on 2022-07-08 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unitofmeasure', '0006_alter_unitofmeasure_de_uom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasureconversion',
            name='ID_CVN_UOM_FM',
            field=models.ForeignKey(blank=True, db_column='CD_CVN_UOM_FM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uom_conversion', to='unitofmeasure.unitofmeasure'),
        ),
    ]
