# Generated by Django 4.0.4 on 2022-07-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitofmeasure', '0007_alter_unitofmeasureconversion_id_cvn_uom_fm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='STATUS_UOM',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=2, verbose_name='UnitOfMeasure Staus'),
        ),
    ]
