# Generated by Django 4.0.4 on 2022-06-16 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellingrule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchandiseHierarchyFunction',
            fields=[
                ('ID_MRHRC_FNC', models.BigAutoField(primary_key=True, serialize=False, verbose_name='MerchandiseHierarchyFunctionID')),
                ('NM_MRHRC_FNC', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'db_table': 'CO_MRHRC_FNC',
            },
        ),
        migrations.CreateModel(
            name='MerchandiseHierarchyLevel',
            fields=[
                ('ID_MRHRC_LV', models.BigAutoField(primary_key=True, serialize=False, verbose_name='MerchandiseHierarchyLevelID')),
                ('DE_MRHRC_LV', models.CharField(max_length=40, verbose_name='Name')),
                ('ID_MRHRC_FNC', models.ForeignKey(db_column='ID_MRHRC_FNC', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.merchandisehierarchyfunction', verbose_name='MerchandiseHierarchyFunctionID')),
                ('ID_MRHRC_LV_PRNT', models.ForeignKey(db_column='ID_MRHRC_LV_PRNT', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.merchandisehierarchylevel', verbose_name='ParentMerchandiseHierarchyLevelID')),
            ],
            options={
                'db_table': 'CO_MRHRC_LV',
            },
        ),
        migrations.CreateModel(
            name='MerchandiseHierarchyGroup',
            fields=[
                ('ID_MRHRC_GP', models.BigAutoField(primary_key=True, serialize=False, verbose_name='MerchandiseHierarchyGroupID')),
                ('NM_MRHRC_GP', models.CharField(max_length=255, verbose_name='Name')),
                ('DE_MRHRC_GP', models.CharField(max_length=255, verbose_name='Description')),
                ('ID_RU_ITM_SL', models.ForeignKey(db_column='ID_RU_ITM_SL', on_delete=django.db.models.deletion.CASCADE, to='sellingrule.itemsellingrule', verbose_name='ItemSellingRuleID')),
            ],
            options={
                'db_table': 'CO_MRHRC_GP',
            },
        ),
        migrations.CreateModel(
            name='AssociatedMerchandiseHierarchyGroup',
            fields=[
                ('ID_ASCTN_MRHRC', models.BigAutoField(primary_key=True, serialize=False, verbose_name='AssociatedMerchandiseHierarchyGroupID')),
                ('DC_EF', models.DateTimeField(verbose_name='EffectiveDate')),
                ('DC_EP', models.DateTimeField(verbose_name='ExpirationDate')),
                ('ID_MRHRC_FNC', models.ForeignKey(db_column='ID_MRHRC_FNC', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.merchandisehierarchyfunction', verbose_name='MerchandiseHierarchyFunctionID')),
                ('ID_MRHRC_GP_CHLD', models.ForeignKey(db_column='ID_MRHRC_GP_CHLD', on_delete=django.db.models.deletion.CASCADE, related_name='ASCTN_MRHRC_CHLD', to='taxonomy.merchandisehierarchygroup', verbose_name='ChildMerchandiseHierarchyGroupID')),
                ('ID_MRHRC_GP_PRNT', models.ForeignKey(db_column='ID_MRHRC_GP_PRNT', on_delete=django.db.models.deletion.CASCADE, related_name='ASCTN_MRHRC_PRNT', to='taxonomy.merchandisehierarchygroup', verbose_name='ParentMerchandiseHierarchyGroupID')),
                ('ID_MRHRC_LV_PRNT', models.ForeignKey(db_column='ID_MRHRC_LV_PRNT', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.merchandisehierarchylevel', verbose_name='ParentMerchandiseHierarchyLevelID')),
            ],
            options={
                'db_table': 'ST_ASCTN_MRHRC',
            },
        ),
    ]
