# Generated by Django 4.0.4 on 2022-06-16 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('CD_CLR', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='ColorCode')),
                ('NM_CLR', models.CharField(max_length=40, verbose_name='Name')),
                ('DE_CLR', models.CharField(max_length=255, verbose_name='Description')),
                ('DE_MDFR', models.CharField(max_length=255, verbose_name='Modification')),
            ],
            options={
                'db_table': 'CO_CLR',
            },
        ),
        migrations.CreateModel(
            name='ColorListAgency',
            fields=[
                ('ID_AGY_CLR_LST', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ColorListAgencyID')),
                ('NM_AGY_CLR_LST', models.CharField(max_length=40, verbose_name='Name')),
            ],
            options={
                'db_table': 'PA_AGY_CLR_LST',
            },
        ),
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('ID_PLTE_CLR', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ColorPaletteID')),
                ('NM_PLTE_CLR', models.CharField(max_length=40, verbose_name='Name')),
                ('DE_PLTE_CLR', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'db_table': 'CO_PLTE_CLR',
            },
        ),
        migrations.CreateModel(
            name='SizeFamily',
            fields=[
                ('ID_SZ_FMY', models.BigAutoField(primary_key=True, serialize=False, verbose_name='SizeFamilyID')),
                ('NM_SZ_FMY', models.CharField(max_length=40, verbose_name='SizeFamilyName')),
                ('DE_SZ_FMY', models.CharField(max_length=40, verbose_name='SizeFamilyDescription')),
            ],
            options={
                'db_table': 'CO_SZ_FMY',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('LU_STYL', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='StyleCode')),
                ('DE_STYL', models.CharField(max_length=255, verbose_name='Description')),
                ('NM_STYL', models.CharField(max_length=40, verbose_name='Name')),
            ],
            options={
                'db_table': 'CO_STYL',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('CD_SZ', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='SizeCode')),
                ('ED_TB_SZ', models.CharField(max_length=2, verbose_name='TableCode')),
                ('NM_TB_SZ', models.CharField(max_length=40, verbose_name='TableName')),
                ('DE_TB_SZ', models.CharField(max_length=255, verbose_name='Description')),
                ('ED_SZ_ACT', models.CharField(max_length=4, verbose_name='ActualSizeCode')),
                ('DE_TYP_ACT_SZ', models.CharField(max_length=40, verbose_name='ActualSizeTypeDescription')),
                ('DE_PRPTN_ACT_SZ', models.CharField(max_length=255, verbose_name='ActualSizeProportionDescription')),
                ('ID_SZ_FMY', models.ForeignKey(db_column='ID_SZ_FMY', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.sizefamily', verbose_name='SizeFamilyID')),
            ],
            options={
                'db_table': 'CO_SZ',
            },
        ),
        migrations.CreateModel(
            name='MerchandiseHierarchyGroupStyle',
            fields=[
                ('ID_MRGP_STYL', models.BigAutoField(primary_key=True, serialize=False, verbose_name='MerchandiseHierarchyGroupStyleID')),
                ('ID_MRHRC_GP', models.ForeignKey(db_column='ID_MRHRC_GP', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.merchandisehierarchygroup', verbose_name='MerchandiseHierarchyGroupID')),
                ('LU_STYL', models.ForeignKey(db_column='LU_STYL', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.style', verbose_name='StyleCode')),
            ],
            options={
                'db_table': 'CO_MRGP_STYL',
            },
        ),
        migrations.CreateModel(
            name='MerchandiseHierarchyGroupSize',
            fields=[
                ('ID_MRGP_SZ', models.BigAutoField(primary_key=True, serialize=False, verbose_name='MerchandiseHierarchyGroupSizeID')),
                ('CD_SZ', models.ForeignKey(db_column='CD_SZ', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.size', verbose_name='SizeCode')),
                ('ID_MRHRC_GP', models.ForeignKey(db_column='ID_MRHRC_GP', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.merchandisehierarchygroup', verbose_name='MerchandiseHierarchyGroupID')),
                ('ID_SZ_FMY', models.ForeignKey(db_column='ID_SZ_FMY', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.sizefamily', verbose_name='SizeFamilyID')),
            ],
            options={
                'db_table': 'CO_MRGP_SZ',
            },
        ),
        migrations.CreateModel(
            name='MerchandiseHierarchyGroupColorPalette',
            fields=[
                ('ID_MRGP_PLTE_CLR', models.BigAutoField(primary_key=True, serialize=False, verbose_name='MerchandiseHierarchyGroupColorPaletteID')),
                ('ID_MRHRC_GP', models.ForeignKey(db_column='ID_MRHRC_GP', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.merchandisehierarchygroup', verbose_name='MerchandiseHierarchyGroupID')),
                ('ID_PLTE_CLR', models.ForeignKey(db_column='ID_PLTE_CLR', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.colorpalette', verbose_name='ColorPaletteID')),
            ],
            options={
                'db_table': 'CO_MRGP_PLTE_CLR',
            },
        ),
        migrations.CreateModel(
            name='MerchandiseHierarchyGroupColor',
            fields=[
                ('ID_MRGP_CLR', models.BigAutoField(primary_key=True, serialize=False, verbose_name='MerchandiseHierarchyGroupColorID')),
                ('CD_CLR', models.ForeignKey(db_column='CD_CLR', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.color', verbose_name='ColorCode')),
                ('ID_MRHRC_GP', models.ForeignKey(db_column='ID_MRHRC_GP', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.merchandisehierarchygroup', verbose_name='MerchandiseHierarchyGroupID')),
            ],
            options={
                'db_table': 'CO_MRGP_CLR',
            },
        ),
        migrations.AddField(
            model_name='color',
            name='ID_AGY_CLR_LST',
            field=models.ForeignKey(db_column='ID_AGY_CLR_LST', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.colorlistagency', verbose_name='ColorListAgencyID'),
        ),
        migrations.AddField(
            model_name='color',
            name='ID_PLTE_CLR',
            field=models.ForeignKey(db_column='ID_PLTE_CLR', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.colorpalette', verbose_name='ColorPaletteID'),
        ),
    ]
