# Generated by Django 4.0.4 on 2022-06-27 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_color_colorlistagency_colorpalette_sizefamily_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandisehierarchylevel',
            name='ID_MRHRC_LV_PRNT',
            field=models.ForeignKey(db_column='ID_MRHRC_LV_PRNT', null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.merchandisehierarchylevel', verbose_name='ParentMerchandiseHierarchyLevelID'),
        ),
    ]
