# Generated by Django 4.0.4 on 2022-07-18 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_customformfield_customformfieldtype_and_more'),
        ('taxonomy', '0003_alter_merchandisehierarchylevel_id_mrhrc_lv_prnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchandiseTemplate',
            fields=[
                ('ID_MRHRC_TMP', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Taxonomy Master Template Id')),
                ('merchandisetemplatename', models.CharField(help_text='Name', max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Description', null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2, verbose_name='Status Code')),
                ('isdefault', models.BooleanField(blank=True, default=False, help_text='Is it default?', null=True, verbose_name='isdefault')),
                ('isdeleted', models.BooleanField(blank=True, default=False, help_text='Is Deleted?', null=True, verbose_name='isdeleted')),
                ('createdby', models.IntegerField(null=True, verbose_name='Created By')),
                ('createddate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updatedby', models.IntegerField(null=True, verbose_name='Updated By')),
                ('updateddate', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Date')),
            ],
            options={
                'db_table': 'CO_MRHRC_TMP',
            },
        ),
        migrations.CreateModel(
            name='MerchandiseTemplateControls',
            fields=[
                ('ID_MRHRC_TMP_CNT', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Template control Id')),
                ('merchandisetemplatecontroldescription', models.TextField(blank=True, help_text='Description', null=True, verbose_name='Description')),
                ('ismandatory', models.BooleanField(blank=True, default=False, help_text='Is it mandatory?', null=True, verbose_name='Is it mandatory?')),
                ('ishidden', models.BooleanField(blank=True, default=False, help_text='Is hidden?', null=True, verbose_name='Is hidden?')),
                ('isfilterable', models.BooleanField(blank=True, default=False, help_text='Is filterable?', null=True, verbose_name='Is filterable?')),
                ('isvalidation', models.BooleanField(blank=True, default=False, help_text='Is validation required?', null=True, verbose_name='Is validation required?')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2, verbose_name='Status Code')),
                ('isdefault', models.BooleanField(blank=True, default=False, help_text='Is it default?', null=True, verbose_name='isdefault')),
                ('isdeleted', models.BooleanField(blank=True, default=False, help_text='Is Deleted?', null=True, verbose_name='isdeleted')),
                ('createdby', models.IntegerField(null=True, verbose_name='Created By')),
                ('createddate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updatedby', models.IntegerField(null=True, verbose_name='Updated By')),
                ('updateddate', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Date')),
                ('ID_BA_CFF', models.ForeignKey(blank=True, db_column='ID_BA_CFF', help_text='Custom form field Identity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_formfield', to='basics.customformfield', verbose_name='Custom form field Id')),
                ('ID_MRHRC_TMP', models.ForeignKey(db_column='ID_MRHRC_TMP', help_text='Taxonomy Template Id', on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_template', to='taxonomy.merchandisetemplate', verbose_name='Taxonomy Template Id')),
            ],
            options={
                'db_table': 'CO_MRHRC_TMP_CNT',
            },
        ),
        migrations.CreateModel(
            name='MerchandiseTemplateType',
            fields=[
                ('ID_MRHRC_TMP_TYP', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Taxonomy Master Template Type Id')),
                ('merchandisetemplatetypename', models.CharField(help_text='Master template type name', max_length=255, unique=True, verbose_name='Master template type name')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2, verbose_name='Status Code')),
                ('isdeleted', models.BooleanField(blank=True, default=False, help_text='Is Deleted?', null=True, verbose_name='isdeleted')),
                ('createdby', models.IntegerField(null=True, verbose_name='Created By')),
                ('createddate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updatedby', models.IntegerField(null=True, verbose_name='Updated By')),
                ('updateddate', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Date')),
            ],
            options={
                'db_table': 'CO_MRHRC_TMP_TYP',
            },
        ),
        migrations.CreateModel(
            name='MerchandiseTemplateControlValue',
            fields=[
                ('ID_MRHRC_TMP_CNT_VL', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Template control value Id')),
                ('merchandisetemplatecontrol_value', models.TextField(blank=True, help_text='Template control value', null=True, verbose_name='Template control value')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2, verbose_name='Status Code')),
                ('isdefault', models.BooleanField(blank=True, default=False, help_text='Is it default?', null=True, verbose_name='isdefault')),
                ('isdeleted', models.BooleanField(blank=True, default=False, help_text='Is Deleted?', null=True, verbose_name='isdeleted')),
                ('ID_BA_CFF_VAL', models.ForeignKey(blank=True, db_column='ID_BA_CFF_VAL', help_text='Custom form field value Identity', null=True, on_delete=django.db.models.deletion.CASCADE, to='basics.customformfieldvalue', verbose_name='Custom form field value Id')),
                ('ID_MRHRC_TMP_CNT', models.ForeignKey(db_column='ID_MRHRC_TMP_CNT', help_text='Taxonomy Template control Id', on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_template_control', to='taxonomy.merchandisetemplatecontrols', verbose_name='Taxonomy Template control Id')),
            ],
            options={
                'db_table': 'CO_MRHRC_TMP_CNT_VL',
            },
        ),
        migrations.AddField(
            model_name='merchandisetemplate',
            name='ID_MRHRC_TMP_TYP',
            field=models.ForeignKey(db_column='ID_MRHRC_TMP_TYP', help_text='Master taxonomy template type Identity', on_delete=django.db.models.deletion.CASCADE, related_name='template_type', to='taxonomy.merchandisetemplatetype', verbose_name='Taxonomy Master Template Type Id'),
        ),
    ]
