# Generated by Django 4.0.4 on 2022-07-14 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0007_alter_businessunit_cd_cny_iso_4217_and_more'),
        ('product', '0008_posdepartment_createdby_posdepartment_createddate_and_more'),
        ('sellingrule', '0009_remove_itemsellingrule_lu_gp_tnd_rst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnitGroupPOSDepartment',
            fields=[
                ('ID_BSNGP_DPT_PS', models.BigAutoField(primary_key=True, serialize=False, verbose_name='BusinessUnitGroupPOSDepartmentID')),
                ('TS_EF', models.DateTimeField(blank=True, null=True, verbose_name='EffectiveDateTime')),
                ('TS_EP', models.DateTimeField(blank=True, null=True, verbose_name='ExpirationDateTime')),
                ('NM_DPT_POS', models.CharField(blank=True, help_text='The title or label given to a point-of-sale department.', max_length=40, null=True, verbose_name='Name')),
                ('ID_BSNGP', models.ForeignKey(db_column='ID_BSNGP', on_delete=django.db.models.deletion.CASCADE, to='store.businessunitgroup', verbose_name='BusinessUnitGroupID')),
                ('ID_DPT_PS', models.ForeignKey(db_column='ID_DPT_PS', on_delete=django.db.models.deletion.CASCADE, to='product.posdepartment', verbose_name='POSDepartmentID')),
                ('ID_ITM_SL_PRC', models.ForeignKey(blank=True, db_column='ID_ITM_SL_PRC', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.itemsellingprices', verbose_name='ItemSellingPricesID')),
                ('ID_RU_ITM_SL', models.ForeignKey(blank=True, db_column='ID_RU_ITM_SL', null=True, on_delete=django.db.models.deletion.CASCADE, to='sellingrule.itemsellingrule', verbose_name='ItemSellingRuleID')),
            ],
            options={
                'db_table': 'CO_BSNGP_DPT_PS',
            },
        ),
    ]
