# Generated by Django 4.0.4 on 2022-06-07 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0001_initial'),
        ('job', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('ID_OPR', models.BigAutoField(primary_key=True, serialize=False, verbose_name='OperatorID')),
                ('PW_ACS_OPR', models.CharField(max_length=20, verbose_name='AccessPassword')),
                ('NM_USR', models.CharField(max_length=40, verbose_name='UserName')),
            ],
            options={
                'db_table': 'PA_OPR',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('ID_RS', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ResourceID')),
                ('DE_RS', models.CharField(max_length=255, verbose_name='Description')),
                ('ID_RS_PRNT', models.ForeignKey(db_column='ID_RS_PRNT', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.resource', verbose_name='ParentResourceID')),
            ],
            options={
                'db_table': 'PA_RS',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('ID_TSK', models.BigAutoField(primary_key=True, serialize=False, verbose_name='TaskID')),
                ('NM_TSK', models.CharField(max_length=40, verbose_name='TaskName')),
                ('DE_TSK', models.CharField(max_length=255, verbose_name='TaskDescription')),
            ],
            options={
                'db_table': 'CO_TSK',
            },
        ),
        migrations.CreateModel(
            name='TaskSet',
            fields=[
                ('ID_ST_TSK', models.BigAutoField(primary_key=True, serialize=False, verbose_name='TaskSetID')),
                ('NM_ST_TSK', models.CharField(max_length=40, verbose_name='Name')),
            ],
            options={
                'db_table': 'CO_ST_TSK',
            },
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('ID_GP_WRK', models.BigAutoField(primary_key=True, serialize=False, verbose_name='WorkGroupID')),
                ('DE_GP_WRK', models.CharField(max_length=255, verbose_name='Description')),
                ('ID_GP_WRK_PRNT', models.ForeignKey(db_column='ID_GP_WRK_PRNT', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.workgroup', verbose_name='ParentWorkGroupID')),
            ],
            options={
                'db_table': 'CO_GP_WRK',
            },
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('ID_WS', models.BigAutoField(primary_key=True, serialize=False, verbose_name='WorkstationID')),
                ('NM_WS_MF', models.CharField(max_length=40, verbose_name='ManufacturerName')),
                ('NM_MDL_WS_TML', models.CharField(max_length=40, verbose_name='TerminalModelNumber')),
                ('SC_TML_WS', models.CharField(choices=[('A', 'Active'), ('C', 'Closed'), ('O', 'Off-Line')], default='A', max_length=2, verbose_name='TerminalStatusCode')),
                ('QU_TL_WS', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='TillCount')),
                ('TY_WS', models.CharField(choices=[], max_length=4, verbose_name='TypeCode')),
                ('FL_MOD_TRG', models.BooleanField(default=False, verbose_name='TrainingModeFlag')),
                ('FL_WS_OTSD', models.BooleanField(default=False, verbose_name='OutsideFlag')),
                ('NM_ADS_DVC', models.CharField(max_length=40, verbose_name='DeviceAddress')),
            ],
            options={
                'db_table': 'AS_WS',
            },
        ),
        migrations.CreateModel(
            name='WorkstationGroup',
            fields=[
                ('ID_WSGP', models.BigAutoField(primary_key=True, serialize=False, verbose_name='WorkstationGroupID')),
                ('NM_WSGP', models.CharField(max_length=255, verbose_name='Name')),
                ('ID_WSGP_PRNT', models.ForeignKey(db_column='ID_WSGP_PRNT', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.workstationgroup', verbose_name='ParentWorkstationGroupID')),
            ],
            options={
                'db_table': 'CO_WSGP',
            },
        ),
        migrations.CreateModel(
            name='WorkstationSiteAssignment',
            fields=[
                ('ID_ASGMT_WS_STE', models.BigAutoField(primary_key=True, serialize=False, verbose_name='WorkstationSiteAssignmentID')),
                ('DC_EF', models.DateTimeField(verbose_name='EffectiveDate')),
                ('NO_WS', models.IntegerField(unique=True, verbose_name='WorkstationNumber')),
                ('DC_EP', models.DateTimeField(verbose_name='ExpirationDate')),
                ('ID_WS', models.ForeignKey(db_column='ID_WS', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.workstation', verbose_name='WorkstationID')),
            ],
            options={
                'db_table': 'CO_ASGMT_WS_STE',
            },
        ),
        migrations.CreateModel(
            name='WorkstationResourceAccess',
            fields=[
                ('ID_ACS_WS_RS', models.BigAutoField(primary_key=True, serialize=False, verbose_name='WorkstationResourceAccessID')),
                ('PS_ACS_RD', models.CharField(choices=[('NA', 'No Access'), ('GA', 'Group Access'), ('UA', 'User Access')], default='NA', max_length=2, verbose_name='ReadAccessLevelCode')),
                ('PS_ACS_WR', models.CharField(choices=[('NA', 'No Access'), ('GA', 'Group Access'), ('UA', 'User Access')], default='NA', max_length=2, verbose_name='WriteAccessLevelCode')),
                ('ID_RS', models.ForeignKey(db_column='ID_RS', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.resource', verbose_name='ResourceID')),
                ('ID_WS', models.ForeignKey(db_column='ID_WS', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.workstation', verbose_name='WorkstationID')),
            ],
            options={
                'db_table': 'CO_ACS_WS_RS',
            },
        ),
        migrations.CreateModel(
            name='WorkstationLocationAssignment',
            fields=[
                ('ID_ASGMT_WS_LCN', models.BigAutoField(primary_key=True, serialize=False, verbose_name='WorkstationLocationAssignmentID')),
                ('DC_EF', models.DateTimeField(verbose_name='EffectiveDate')),
                ('NU_WS', models.IntegerField(unique=True, verbose_name='WorkstationNumber')),
                ('DC_EP', models.DateTimeField(verbose_name='ExpirationDate')),
                ('ID_LCN', models.ForeignKey(db_column='ID_LCN', on_delete=django.db.models.deletion.CASCADE, to='store.worklocation', verbose_name='LocationID')),
                ('ID_WS', models.ForeignKey(db_column='ID_WS', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.workstation', verbose_name='WorkstationID')),
            ],
            options={
                'db_table': 'CO_ASGMT_WS_LCN',
            },
        ),
        migrations.CreateModel(
            name='WorkstationGroupResourceAccess',
            fields=[
                ('ID_ACS_WSGP_RS', models.BigAutoField(primary_key=True, serialize=False, verbose_name='WorkstationGroupResourceAccessID')),
                ('ID_RS', models.ForeignKey(db_column='ID_RS', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.resource', verbose_name='ResourceID')),
                ('ID_WSGP', models.ForeignKey(db_column='ID_WSGP', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.workstationgroup', verbose_name='WorkstationGroupID')),
            ],
            options={
                'db_table': 'CO_ACS_WSGP_RS',
            },
        ),
        migrations.AddField(
            model_name='workstation',
            name='ID_WSGP',
            field=models.ForeignKey(db_column='ID_WSGP', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.workstationgroup', verbose_name='WorkstationGroupID'),
        ),
        migrations.CreateModel(
            name='WorkGroupWorkstationGroupResourceAccess',
            fields=[
                ('ID_ACS_WKGP_WSGP_RS', models.BigAutoField(primary_key=True, serialize=False, verbose_name='WorkGroupWorkstationGroupResourceAccessID')),
                ('ID_GP_WRK', models.ForeignKey(db_column='ID_GP_WRK', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.workgroup', verbose_name='WorkGroupID')),
                ('ID_RS', models.ForeignKey(db_column='ID_RS', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.resource', verbose_name='ResourceID')),
                ('ID_WSGP', models.ForeignKey(db_column='ID_WSGP', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.workstationgroup', verbose_name='WorkstationGroupID')),
            ],
            options={
                'db_table': 'CO_ACS_WKGP_WSGP_RS',
            },
        ),
        migrations.CreateModel(
            name='WorkerOperatorAssignment',
            fields=[
                ('ID_ASGMT_WRKR_OPR', models.BigAutoField(primary_key=True, serialize=False, verbose_name='WorkerOperatorAssignmentID')),
                ('TS_EF', models.DateTimeField(verbose_name='EffectiveDateTime')),
                ('TS_EP', models.DateTimeField(verbose_name='ExpirationDateTime')),
                ('SC_ASGMT', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2, verbose_name='Status Code')),
                ('ID_OPR', models.ForeignKey(db_column='ID_OPR', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.operator', verbose_name='OperatorID')),
                ('ID_WRKR', models.ForeignKey(db_column='ID_WRKR', on_delete=django.db.models.deletion.CASCADE, to='worker.worker', verbose_name='WorkerID')),
            ],
            options={
                'db_table': 'CO_ASGMT_WRKR_OPR',
            },
        ),
        migrations.CreateModel(
            name='TaskResourceAccess',
            fields=[
                ('ID_ACS_TSK_RS', models.BigAutoField(primary_key=True, serialize=False, verbose_name='TaskResourceAccessID')),
                ('ID_RS', models.ForeignKey(db_column='ID_RS', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.resource', verbose_name='ResourceID')),
                ('ID_TSK', models.ForeignKey(db_column='ID_TSK', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.task', verbose_name='TaskID')),
            ],
            options={
                'db_table': 'CO_ACS_TSK_RS',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='ID_ST_TSK',
            field=models.ForeignKey(db_column='ID_ST_TSK', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.taskset', verbose_name='TaskSetID'),
        ),
        migrations.CreateModel(
            name='OperatorResourceAccess',
            fields=[
                ('ID_ACS_OPR_RS', models.BigAutoField(primary_key=True, serialize=False, verbose_name='OperatorResourceAccessID')),
                ('PS_ACS_RD', models.CharField(choices=[('NA', 'No Access'), ('GA', 'Group Access'), ('UA', 'User Access')], default='NA', max_length=2, verbose_name='ReadAccessLevelCode')),
                ('PR_ACS_WR', models.CharField(choices=[('NA', 'No Access'), ('GA', 'Group Access'), ('UA', 'User Access')], default='NA', max_length=2, verbose_name='WriteAccessLevelCode')),
                ('ID_OPR', models.ForeignKey(db_column='ID_OPR', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.operator', verbose_name='OperatorID')),
                ('ID_RS', models.ForeignKey(db_column='ID_RS', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.resource', verbose_name='ResourceID')),
            ],
            options={
                'db_table': 'CO_ACS_OPR_RS',
            },
        ),
        migrations.CreateModel(
            name='OperatorGroup',
            fields=[
                ('ID_GP_OPR', models.BigAutoField(primary_key=True, serialize=False, verbose_name='OperatorGroupID')),
                ('ID_GP_WRK', models.ForeignKey(db_column='ID_GP_WRK', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.workgroup', verbose_name='WorkGroupID')),
                ('ID_OPR', models.ForeignKey(db_column='ID_OPR', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.operator', verbose_name='OperatorID')),
            ],
            options={
                'db_table': 'CO_GP_OPR',
            },
        ),
        migrations.CreateModel(
            name='OperatorBusinessUnitAssignment',
            fields=[
                ('ID_ASGMT_OPR_LCN', models.BigAutoField(primary_key=True, serialize=False, verbose_name='OperatorBusinessUnitAssignmentID')),
                ('TS_EF', models.DateTimeField(verbose_name='EffectiveDateTime')),
                ('TS_EP', models.DateTimeField(verbose_name='ExpirationDateTime')),
                ('NU_OPR', models.IntegerField(unique=True, verbose_name='OperatorNumber')),
                ('ID_BSN_UN', models.ForeignKey(db_column='ID_BSN_UN', on_delete=django.db.models.deletion.CASCADE, to='store.businessunit', verbose_name='BusinessUnitID')),
                ('ID_OPR', models.ForeignKey(db_column='ID_OPR', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.operator', verbose_name='OperatorID')),
            ],
            options={
                'db_table': 'CO_ASGMT_OPR_LCN',
            },
        ),
        migrations.CreateModel(
            name='JobTaskSet',
            fields=[
                ('ID_JOB_ST_TSK', models.BigAutoField(primary_key=True, serialize=False, verbose_name='JobTaskSetID')),
                ('ID_JOB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job', verbose_name='JobID')),
                ('ID_ST_TSK', models.ForeignKey(db_column='ID_ST_TSK', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.taskset', verbose_name='TaskSetID')),
            ],
            options={
                'db_table': 'ST_JOB_ST_TSK',
            },
        ),
        migrations.CreateModel(
            name='GroupResourceAccess',
            fields=[
                ('ID_ACS_GP_RS', models.BigAutoField(primary_key=True, serialize=False, verbose_name='GroupResourceAccessID')),
                ('FL_ACS_GP_RD', models.BooleanField(default=True, verbose_name='GroupReadAccessLevelFlag')),
                ('FL_ACS_GP_WR', models.BooleanField(default=True, verbose_name='GroupWriteAccessLevelFlag')),
                ('ID_GP_WRK', models.ForeignKey(db_column='ID_GP_WRK', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.workgroup', verbose_name='WorkGroupID')),
                ('ID_RS', models.ForeignKey(db_column='ID_RS', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.resource', verbose_name='ResourceID')),
            ],
            options={
                'db_table': 'CO_ACS_GP_RS',
            },
        ),
        migrations.CreateModel(
            name='AccessPassword',
            fields=[
                ('AI_ACS_PSWD', models.BigAutoField(primary_key=True, serialize=False, verbose_name='AccessPasswordSequenceNumber')),
                ('PS_ACS_OPR', models.CharField(max_length=20, verbose_name='Password')),
                ('TS_EP', models.DateTimeField(verbose_name='ExpirationDateTime')),
                ('ID_OPR', models.ForeignKey(blank=True, db_column='ID_OPR', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accesscontrol.operator', verbose_name='OperatorID')),
            ],
            options={
                'db_table': 'CO_ACS_PSWD',
            },
        ),
    ]
