# Generated by Django 4.0.4 on 2022-06-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0002_alter_workgroup_id_gp_wrk_prnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='ID_RS_PRNT',
            field=models.ForeignKey(blank=True, db_column='ID_RS_PRNT', null=True, on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.resource', verbose_name='ParentResourceID'),
        ),
    ]
