# Generated by Django 4.0.4 on 2022-06-27 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0003_alter_resource_id_rs_prnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstationgroup',
            name='ID_WSGP_PRNT',
            field=models.ForeignKey(db_column='ID_WSGP_PRNT', null=True, on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.workstationgroup', verbose_name='ParentWorkstationGroupID'),
        ),
    ]
