# Generated by Django 4.0.4 on 2022-07-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0005_operator_accs_typ_opr_operator_email_usr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='createdby',
            field=models.IntegerField(null=True, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='operator',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='operator',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2, verbose_name='Status Code'),
        ),
        migrations.AddField(
            model_name='operator',
            name='updatedby',
            field=models.IntegerField(null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='operator',
            name='updateddate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Date'),
        ),
    ]
