# Generated by Django 4.0.4 on 2022-07-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0007_resource_display_order_resource_is_visible_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, help_text='Created date', null=True),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='createdby',
            field=models.IntegerField(help_text='Created By', null=True),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='status',
            field=models.CharField(blank=True, help_text='Workgroup status (Active/Inactive)', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='updatedat',
            field=models.DateTimeField(auto_now_add=True, help_text='Last update date', null=True),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='updatedby',
            field=models.IntegerField(help_text='Updated By', null=True),
        ),
    ]
