# Generated by Django 4.0.4 on 2022-07-26 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_businessunit_cd_cny_iso_4217_and_more'),
        ('accesscontrol', '0008_workgroup_createdat_workgroup_createdby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreWorkGroup',
            fields=[
                ('storeworkgroup_id', models.AutoField(help_text='Storeworkgroup Identity', primary_key=True, serialize=False)),
                ('ID_BSN_UN', models.ForeignKey(help_text='Store Identity', on_delete=django.db.models.deletion.CASCADE, to='store.businessunit')),
                ('ID_GP_WRK', models.ForeignKey(help_text='Work Group Identity', on_delete=django.db.models.deletion.CASCADE, to='accesscontrol.workgroup')),
            ],
            options={
                'db_table': 'store_workgroup',
            },
        ),
    ]
