# Generated by Django 4.0.4 on 2022-07-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0009_storeworkgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workgroup',
            old_name='createdat',
            new_name='createddate',
        ),
        migrations.RenameField(
            model_name='workgroup',
            old_name='updatedat',
            new_name='updateddate',
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='DE_GP_WRK',
            field=models.CharField(max_length=255, unique=True, verbose_name='Description'),
        ),
    ]
