# Generated by Django 4.0.4 on 2022-07-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0010_rename_createdat_workgroup_createddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='NM_GP_WRK',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='WorkGroupName'),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='access_type',
            field=models.CharField(blank=True, help_text='Workgroup Access Type', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='welcome_screen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='DE_GP_WRK',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
