# Generated by Django 4.0.4 on 2022-07-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0011_workgroup_nm_gp_wrk_workgroup_access_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='access_type',
            field=models.CharField(blank=True, choices=[('Backend', 'Backend'), ('POS Terminal', 'POS Terminal')], default='Backend', help_text='Workgroup Access Type', max_length=40, null=True),
        ),
    ]
