# Generated by Django 4.0.4 on 2022-07-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontrol', '0012_alter_workgroup_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive')], help_text='Workgroup status (Active/Inactive)', max_length=8, null=True),
        ),
    ]
