# Generated by Django 4.0.4 on 2022-06-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_businessunitgrouplevel_id_bsngp_fnce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedBusinessUnitGroup',
            fields=[
                ('ID_ASCTN_BSNGP', models.BigAutoField(primary_key=True, serialize=False, verbose_name='AssociatedBusinessUnitGroupID')),
                ('DC_EF', models.DateTimeField(verbose_name='EffectiveDate')),
                ('DC_EP', models.DateTimeField(verbose_name='ExpirationDate')),
                ('ID_BSNGP_CHLD', models.ForeignKey(db_column='ID_BSNGP_CHLD', on_delete=django.db.models.deletion.CASCADE, related_name='BSNGP_CHLD', to='store.businessunitgroup', verbose_name='ChildBusinessUnitGroupID')),
                ('ID_BSNGP_FNC', models.ForeignKey(db_column='ID_BSNGP_FNC', on_delete=django.db.models.deletion.CASCADE, to='store.businessunitgroupfunction', verbose_name='BusinessUnitGroupFunctionID')),
                ('ID_BSNGP_LV', models.ForeignKey(db_column='ID_BSNGP_LV', on_delete=django.db.models.deletion.CASCADE, to='store.businessunitgrouplevel', verbose_name='ParentBusinessUnitGroupLevelID')),
                ('ID_BSNGP_PRNT', models.ForeignKey(db_column='ID_BSNGP_PRNT', on_delete=django.db.models.deletion.CASCADE, related_name='BSNGP_PRNT', to='store.businessunitgroup', verbose_name='ParentBusinessUnitGroupID')),
            ],
            options={
                'db_table': 'ST_ASCTN_BSNGP',
            },
        ),
    ]
