# Generated by Django 4.0.4 on 2022-06-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_associatedbusinessunitgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunitgrouplevel',
            name='ID_BSNGP_LV_PRNT',
            field=models.ForeignKey(db_column='ID_BSNGP_LV_PRNT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BSNGP_LV', to='store.businessunitgrouplevel', verbose_name='BusinessUnitCenterGroupLevelID '),
        ),
    ]
