# Generated by Django 4.0.4 on 2022-07-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerschedule', '0004_timegroup_createdby_timegroup_createddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeperiod',
            name='TM_END',
            field=models.TimeField(blank=True, null=True, verbose_name='EndTime'),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2, verbose_name='Status Code'),
        ),
    ]
