# Generated by Django 4.0.4 on 2022-07-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    ''' Migration Class'''

    dependencies = [
        ('workerschedule', '0005_timeperiod_tm_end_timeperiod_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timegroup',
            name='NM_GP_TM',
            field=models.CharField(
                default='', max_length=40, verbose_name='Title'),
        ),
    ]
