# Generated by Django 4.0.4 on 2022-07-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerschedule', '0006_timegroup_nm_gp_tm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeperiod',
            name='SI_DRN',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Duration'),
        ),
    ]
