# Generated by Django 4.0.4 on 2022-06-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('ID_JOB', models.BigAutoField(primary_key=True, serialize=False, verbose_name='JobID')),
                ('NM_JOB', models.CharField(max_length=40, verbose_name='Name')),
                ('DE_JOB', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('FL_SHR', models.BooleanField(default=False, verbose_name='ShareFlag')),
            ],
            options={
                'db_table': 'CO_JOB',
            },
        ),
    ]
