# Generated by Django 4.0.4 on 2022-07-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='DE_PST',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='MDF_DT',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='ID_LCN',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='CRT_DT',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='NM_TTL',
            new_name='title',
        ),
    ]
