# Generated by Django 4.0.4 on 2022-07-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_rename_de_pst_position_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='start_date',
            new_name='CRT_DT',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='description',
            new_name='DE_PST',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='location',
            new_name='ID_LCN',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='end_date',
            new_name='MDF_DT',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='title',
            new_name='NM_TTL',
        ),
    ]
