# Generated by Django 4.0.4 on 2022-07-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('department', '0002_alter_department_status'),
        ('store', '0007_alter_businessunit_cd_cny_iso_4217_and_more'),
        ('position', '0003_rename_start_date_position_crt_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='ID_DEPT',
            field=models.ForeignKey(db_column='ID_DEPT', null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='DepartmentID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='ID_JOB',
            field=models.ForeignKey(db_column='ID_JOB', null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job', verbose_name='JobID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='ID_LCN',
            field=models.ForeignKey(db_column='ID_LCN', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.worklocation', verbose_name='LocationID'),
        ),
    ]
