# Generated by Django 4.0.4 on 2022-07-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0004_position_id_dept_alter_position_id_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='status',
            field=models.CharField(choices=[('A', 'A'), ('I', 'I')], default='A', max_length=100),
        ),
    ]
