# Generated by Django 4.0.4 on 2022-07-26 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_status'),
        ('position', '0006_position_end_date_position_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='ID_DEPT',
        ),
        migrations.AddField(
            model_name='position',
            name='department_id',
            field=models.ForeignKey(db_column='department_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='DepartmentID'),
        ),
    ]
