# Generated by Django 4.0.4 on 2022-07-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0007_remove_position_id_dept_position_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='createdby',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='updatedby',
            field=models.IntegerField(null=True),
        ),
    ]
