# Generated by Django 4.0.4 on 2022-06-16 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnitGroupItem',
            fields=[
                ('ID_BSNGP_ITM', models.BigAutoField(primary_key=True, serialize=False, verbose_name='BusinessUnitGroupItemID')),
                ('TS_EF', models.DateTimeField(verbose_name='EffectiveDateTime')),
                ('TS_EP', models.DateTimeField(verbose_name='ExpirationDateTime')),
                ('SC_ITM_SLS', models.CharField(max_length=2, verbose_name='SellingStatusCode')),
                ('SC_ITM', models.CharField(max_length=2, verbose_name='StatusCode')),
                ('DC_ITM_SLS', models.DateTimeField(verbose_name='SellingStatusCodeEffectiveDate')),
                ('FL_STK_UPDT_ON_HD', models.IntegerField(verbose_name='UpdateStockOnHandFlag')),
            ],
            options={
                'db_table': 'AS_BSNGP_ITM',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ID_ITM', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ItemID')),
                ('FL_AZN_FR_SLS', models.IntegerField(verbose_name='AuthorizedForSaleFlag')),
                ('FL_ITM_DSC', models.IntegerField(verbose_name='DiscountFlag')),
                ('FL_ADT_ITM_PRC', models.IntegerField(verbose_name='PriceAuditFlag')),
                ('LU_EXM_TX', models.CharField(max_length=2, verbose_name='TaxExemptCode')),
                ('LU_ITM_USG', models.CharField(max_length=2, verbose_name='UsageCode')),
                ('NM_ITM', models.CharField(max_length=40, verbose_name='Name')),
                ('DE_ITM', models.CharField(max_length=255, verbose_name='Description')),
                ('DE_ITM_LNG', models.TextField(verbose_name='LongDescription')),
                ('TY_ITM', models.CharField(max_length=4, verbose_name='TypeCode')),
                ('LU_KT_ST', models.CharField(max_length=2, verbose_name='KitSetCode')),
                ('FL_ITM_SBST_IDN', models.IntegerField(verbose_name='SubstituteIdentifiedFlag')),
                ('LU_CLN_ORD', models.CharField(max_length=2, verbose_name='OrderCollectionCode')),
                ('FL_VLD_SRZ_ITM', models.IntegerField(verbose_name='SerializedIUnitValidationFlag')),
                ('NM_BRN_SUB_BRN', models.CharField(max_length=40, verbose_name='SubBrand Name')),
            ],
            options={
                'db_table': 'AS_ITM',
            },
        ),
        migrations.CreateModel(
            name='ItemSellingPrices',
            fields=[
                ('ID_ITM_SL_PRC', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ItemSellingPricesID')),
                ('RP_PR_SLS', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='PermanentSaleUnitRetailPriceAmount')),
                ('FL_MKD_ORGL_PRC_PR', models.IntegerField(verbose_name='PermanentSaleUnitRetailPriceOriginalMarkdownFlag')),
                ('QU_MKD_PR_PRC_PR', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='PermanentRetailPricePermanentMarkdownCount')),
                ('DC_PRC_EF_PRN_RT', models.DateTimeField(verbose_name='PermanentRetailPriceEffectiveDate')),
                ('RP_SLS_CRT', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='CurrentSaleUnitRetailPriceAmount')),
                ('TY_PRC_RT', models.CharField(max_length=2, verbose_name='CurrentSaleUnitRetailPriceTypeCode')),
                ('FL_PRC_RT_PNT_ALW', models.IntegerField(verbose_name='CurrentSaleUnitRetailPricePointAllowedFlag')),
                ('DC_PRC_SLS_EF_CRT', models.DateTimeField(verbose_name='CurrentSaleUnitRetailPriceEffectiveDate')),
                ('DC_PRC_SLS_EP_CRT', models.DateTimeField(verbose_name='CurrentSaleUnitRetailPriceExpirationDate')),
                ('RP_PRC_MF_RCM_RT', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='ManufacturerSaleUnitRecommendedRetailPriceAmount')),
                ('DC_PRC_MF_RCM_RT', models.DateTimeField(verbose_name='ManufacturerSaleUnitRecommendedRetailPriceEffectiveDate')),
                ('RP_PRC_CMPR_AT_SLS', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='CompareAtSaleUnitRetailPriceAmount')),
                ('FL_QTY_PRC', models.IntegerField(verbose_name='QuantityPricingFlag')),
                ('QU_PCKG_PRC_CRT', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='CurrentPackagePriceQuantity')),
                ('RP_PCKG_PRC_CRT', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='CurrentPackagePrice')),
                ('QU_PCKG_PRC_PRN', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='PermanentPackagePriceQuantity')),
                ('RP_PCKG_PRC_PRN', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='PermanentPackagePrice')),
                ('RP_RTN_UN_PRN_SLS', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='PermanentSaleUnitReturnPrice')),
                ('RP_RTN_UN_CRT_SLS', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='CurrentSaleUnitReturnPrice')),
                ('FL_TX_INC', models.IntegerField(verbose_name='IncludesSalesTaxFlag')),
                ('MO_AMT_TX_PRN', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='PermanentSalesTaxAmount')),
                ('MO_AMT_TX_CRT', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='CurrentSalesTaxAmount')),
                ('RP_MNM_ADVRTSD', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='MinimumAdvertisedRetailUnitPrice')),
                ('DC_EF_RP_MNM_ADVRTSD', models.DateTimeField(verbose_name='MinimumAdvertisedRetailUnitPriceEffectiveDate')),
            ],
            options={
                'db_table': ' RU_ITM_SL_PRC',
            },
        ),
        migrations.CreateModel(
            name='POSDepartment',
            fields=[
                ('ID_DPT_PS', models.BigAutoField(primary_key=True, serialize=False, verbose_name='POSDepartmentID')),
                ('NM_DPT_PS', models.CharField(max_length=40, verbose_name='Name')),
            ],
            options={
                'db_table': 'ID_DPT_PS',
            },
        ),
        migrations.CreateModel(
            name='PriceLine',
            fields=[
                ('ID_LN_PRC', models.BigAutoField(primary_key=True, serialize=False, verbose_name='PriceLineID')),
                ('LL_LN_PRC', models.DecimalField(decimal_places=5, max_digits=16, verbose_name='LowAmount')),
                ('UL_LN_PRC', models.DecimalField(decimal_places=5, max_digits=16, verbose_name='HighAmount')),
            ],
            options={
                'db_table': 'AS_LN_PRC',
            },
        ),
    ]
