# Generated by Django 4.0.4 on 2022-06-16 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('sellingrule', '0001_initial'),
        ('store', '0005_associatedbusinessunitgroup'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceline',
            name='ID_MRHRC_GP',
            field=models.ForeignKey(db_column='ID_MRHRC_GP', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.merchandisehierarchygroup', verbose_name='MerchandiseHierarchyGroupID'),
        ),
        migrations.AddField(
            model_name='posdepartment',
            name='ID_DPT_PS_PRNT',
            field=models.ForeignKey(db_column='ID_DPT_PS_PRNT', on_delete=django.db.models.deletion.CASCADE, to='product.posdepartment', verbose_name='ParentPOSDepartmentID'),
        ),
        migrations.AddField(
            model_name='posdepartment',
            name='ID_RU_ITM_SL',
            field=models.ForeignKey(db_column='ID_RU_ITM_SL', on_delete=django.db.models.deletion.CASCADE, to='sellingrule.itemsellingrule', verbose_name='ItemSellingRuleID'),
        ),
        migrations.AddField(
            model_name='item',
            name='ID_DPT_PS',
            field=models.ForeignKey(db_column='ID_DPT_PS', on_delete=django.db.models.deletion.CASCADE, to='product.posdepartment', verbose_name='POSDepartmentID'),
        ),
        migrations.AddField(
            model_name='item',
            name='ID_ITM_SL_PRC',
            field=models.ForeignKey(db_column='ID_ITM_SL_PRC', on_delete=django.db.models.deletion.CASCADE, to='product.itemsellingprices', verbose_name='ItemSellingPricesID'),
        ),
        migrations.AddField(
            model_name='item',
            name='ID_LN_PRC',
            field=models.ForeignKey(db_column='ID_LN_PRC', on_delete=django.db.models.deletion.CASCADE, to='product.priceline', verbose_name='PriceLineID'),
        ),
        migrations.AddField(
            model_name='item',
            name='ID_MRHRC_GP',
            field=models.ForeignKey(db_column='ID_MRHRC_GP', on_delete=django.db.models.deletion.CASCADE, to='taxonomy.merchandisehierarchygroup', verbose_name='MerchandiseHierarchyGroupID'),
        ),
        migrations.AddField(
            model_name='item',
            name='ID_RU_ITM_SL',
            field=models.ForeignKey(db_column='ID_RU_ITM_SL', on_delete=django.db.models.deletion.CASCADE, to='sellingrule.itemsellingrule', verbose_name='ItemSellingRuleID'),
        ),
        migrations.AddField(
            model_name='businessunitgroupitem',
            name='ID_BSNGP',
            field=models.ForeignKey(db_column='ID_BSNGP', on_delete=django.db.models.deletion.CASCADE, to='store.businessunitgroup', verbose_name='BusinessUnitGroupID'),
        ),
        migrations.AddField(
            model_name='businessunitgroupitem',
            name='ID_ITM',
            field=models.ForeignKey(db_column='ID_ITM', on_delete=django.db.models.deletion.CASCADE, to='product.item', verbose_name='ItemID'),
        ),
        migrations.AddField(
            model_name='businessunitgroupitem',
            name='ID_ITM_SL_PRC',
            field=models.ForeignKey(db_column='ID_ITM_SL_PRC', on_delete=django.db.models.deletion.CASCADE, to='product.itemsellingprices', verbose_name='ItemSellingPricesID'),
        ),
        migrations.AddField(
            model_name='businessunitgroupitem',
            name='ID_RU_ITM_SL',
            field=models.ForeignKey(db_column='ID_RU_ITM_SL', on_delete=django.db.models.deletion.CASCADE, to='sellingrule.itemsellingrule', verbose_name='ItemSellingRuleID'),
        ),
    ]
