# Generated by Django 4.0.4 on 2022-06-21 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='AI_SUB_BRN',
            field=models.ForeignKey(db_column='AI_SUB_BRN', null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.subbrand', verbose_name='SubBrand sequence number'),
        ),
        migrations.AddField(
            model_name='item',
            name='NM_BRN',
            field=models.ForeignKey(db_column='NM_BRN', null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.brand', verbose_name='BrandName'),
        ),
    ]
