# Generated by Django 4.0.4 on 2022-06-27 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_item_ai_sub_brn_item_nm_brn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posdepartment',
            name='ID_DPT_PS_PRNT',
            field=models.ForeignKey(db_column='ID_DPT_PS_PRNT', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.posdepartment', verbose_name='ParentPOSDepartmentID'),
        ),
    ]
