# Generated by Django 4.0.4 on 2022-07-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_posdepartment_id_dpt_ps_prnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunitgroupitem',
            name='DC_ITM_SLS',
            field=models.DateTimeField(null=True, verbose_name='SellingStatusCodeEffectiveDate'),
        ),
    ]
