# Generated by Django 4.0.4 on 2022-07-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_businessunitgroupitem_dc_itm_sls'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsellingprices',
            name='ITM_SL_PRC_STATUS',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive')], help_text='Item Selling Price Rule (Active/Inactive)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='DC_PRC_EF_PRN_RT',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PermanentRetailPriceEffectiveDate'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='DC_PRC_MF_RCM_RT',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ManufacturerSaleUnitRecommendedRetailPriceEffectiveDate'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='DC_PRC_SLS_EF_CRT',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CurrentSaleUnitRetailPriceEffectiveDate'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='DC_PRC_SLS_EP_CRT',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CurrentSaleUnitRetailPriceExpirationDate'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='FL_MKD_ORGL_PRC_PR',
            field=models.IntegerField(blank=True, null=True, verbose_name='PermanentSaleUnitRetailPriceOriginalMarkdownFlag'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='FL_PRC_RT_PNT_ALW',
            field=models.IntegerField(blank=True, null=True, verbose_name='CurrentSaleUnitRetailPricePointAllowedFlag'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='FL_QTY_PRC',
            field=models.IntegerField(blank=True, null=True, verbose_name='QuantityPricingFlag'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='FL_TX_INC',
            field=models.IntegerField(blank=True, null=True, verbose_name='IncludesSalesTaxFlag'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='MO_AMT_TX_CRT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='CurrentSalesTaxAmount'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='MO_AMT_TX_PRN',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='PermanentSalesTaxAmount'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='QU_MKD_PR_PRC_PR',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='PermanentRetailPricePermanentMarkdownCount'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='QU_PCKG_PRC_CRT',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='CurrentPackagePriceQuantity'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='QU_PCKG_PRC_PRN',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='PermanentPackagePriceQuantity'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='RP_MNM_ADVRTSD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='MinimumAdvertisedRetailUnitPrice'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='RP_PCKG_PRC_CRT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='CurrentPackagePrice'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='RP_PCKG_PRC_PRN',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='PermanentPackagePrice'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='RP_PRC_CMPR_AT_SLS',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='CompareAtSaleUnitRetailPriceAmount'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='RP_PRC_MF_RCM_RT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='ManufacturerSaleUnitRecommendedRetailPriceAmount'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='RP_PR_SLS',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='PermanentSaleUnitRetailPriceAmount'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='RP_RTN_UN_CRT_SLS',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='CurrentSaleUnitReturnPrice'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='RP_RTN_UN_PRN_SLS',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='PermanentSaleUnitReturnPrice'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='RP_SLS_CRT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='CurrentSaleUnitRetailPriceAmount'),
        ),
        migrations.AlterField(
            model_name='itemsellingprices',
            name='TY_PRC_RT',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='CurrentSaleUnitRetailPriceTypeCode'),
        ),
    ]
