# Generated by Django 4.0.4 on 2022-07-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_itemsellingprices_itm_sl_prc_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsellingprices',
            name='ITM_SL_PRC_NAME',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ItemSellingPriceRuleName'),
        ),
    ]
