# Generated by Django 4.0.4 on 2022-07-20 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellingrule', '0011_alter_itemsellingrule_expired_date'),
        ('product', '0008_posdepartment_createdby_posdepartment_createddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posdepartment',
            name='ID_RU_ITM_SL',
            field=models.ForeignKey(blank=True, db_column='ID_RU_ITM_SL', null=True, on_delete=django.db.models.deletion.CASCADE, to='sellingrule.itemsellingrule', verbose_name='ItemSellingRuleID'),
        ),
    ]
