# Generated by Django 4.0.4 on 2022-06-06 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('ID_WRKR', models.BigAutoField(primary_key=True, serialize=False, verbose_name='WorkerID')),
                ('TY_WRKR', models.CharField(blank=True, choices=[], max_length=2, null=True, verbose_name='WorkerType Code')),
                ('BM_PGPH_WRKR', models.BinaryField(blank=True, null=True, verbose_name='WorkerPhotograph')),
                ('DE_SPL_RQMT', models.TextField(blank=True, null=True, verbose_name='SpecialRequirements')),
                ('WRKR_CRT_DT', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('WRKR_MDF_DT', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('ID_PRTY_RO_ASGMT', models.ForeignKey(db_column='ID_PRTY_RO_ASGMT', on_delete=django.db.models.deletion.CASCADE, to='party.partyroleassignment', verbose_name='PartyRoleAssignmentID')),
                ('WRKR_CRT_BY', models.ForeignKey(blank=True, db_column='WRKR_CRT_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='WRKR_Createuser', to=settings.AUTH_USER_MODEL)),
                ('WRKR_MDF_BY', models.ForeignKey(blank=True, db_column='WRKR_MDF_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='WRKR_Modifiyuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PA_WRKR',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('ID_VN', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ContractorID')),
                ('TY_VN', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('B2G', 'B2G')], max_length=3, verbose_name='VendorType')),
                ('ID_PRTY_RO_ASGMT', models.ForeignKey(db_column='ID_PRTY_RO_ASGMT', on_delete=django.db.models.deletion.CASCADE, to='party.partyroleassignment', verbose_name='PartyRoleAssignmentID')),
            ],
            options={
                'db_table': 'PA_VN',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID_EM', models.BigAutoField(primary_key=True, serialize=False, verbose_name='EmployeeID')),
                ('SC_EM', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2, verbose_name='StatusCode')),
                ('ID_WRKR', models.ForeignKey(db_column='ID_WRKR', on_delete=django.db.models.deletion.CASCADE, to='worker.worker', verbose_name='WorkerID')),
            ],
            options={
                'db_table': 'PA_EM',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('ID_CNTR', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ContractorID')),
                ('ID_VN', models.ForeignKey(db_column='ID_VN', on_delete=django.db.models.deletion.CASCADE, to='worker.vendor', verbose_name='VendorID')),
                ('ID_WRKR', models.ForeignKey(db_column='ID_WRKR', on_delete=django.db.models.deletion.CASCADE, to='worker.worker', verbose_name='WorkerID')),
            ],
            options={
                'db_table': 'PA_CNTR',
            },
        ),
    ]
