# Generated by Django 4.0.4 on 2022-06-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendor',
            table='TY_VN',
        ),
    ]
