# Generated by Django 4.0.4 on 2022-06-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_alter_vendor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('ID_MF', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ManufacturerID')),
            ],
            options={
                'db_table': 'PA_MF',
            },
        ),
    ]
