# Generated by Django 4.0.4 on 2022-06-08 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPartyIdentificationProvider',
            fields=[
                ('ID_PA_PVR_EXTRN', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ExternalPartyIdentificationProviderID')),
                ('ID_PRTY_RO_ASGMT', models.ForeignKey(db_column='ID_PRTY_RO_ASGMT', on_delete=django.db.models.deletion.CASCADE, to='party.partyroleassignment', verbose_name='PartyRoleAssignmentID')),
            ],
            options={
                'db_table': 'PA_PVR_EXTRN_IDTN',
            },
        ),
        migrations.CreateModel(
            name='LegalOrganizationType',
            fields=[
                ('CD_LGL_ORGN_TYP', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='LegalOrgnizationTypeCode')),
                ('DE_LGL_ORGN_TYP', models.CharField(max_length=255, verbose_name='LeganOrganizationTypeDescription')),
            ],
            options={
                'db_table': 'LU_LGL_ORGN',
            },
        ),
        migrations.CreateModel(
            name='PartyIdentificationType',
            fields=[
                ('TY_PRTY_ID', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='PartyIdentificationTypeCode')),
                ('DE_PRTY_ID', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'db_table': 'PA_TYP_IDTN',
            },
        ),
        migrations.CreateModel(
            name='PartyIdentification',
            fields=[
                ('ID_PA_IDTN', models.BigAutoField(primary_key=True, serialize=False, verbose_name='PartyIdentificationID')),
                ('DT_EF', models.DateTimeField(verbose_name='EffectiveDate')),
                ('LU_ID_PRTY', models.IntegerField(unique=True, verbose_name='Identifier')),
                ('DC_ISS', models.DateTimeField(verbose_name='IssueDate')),
                ('DC_ID_PRTY_EP', models.DateTimeField(verbose_name='ExpirationDate')),
                ('ID_ADS', models.ForeignKey(db_column='ID_ADS', on_delete=django.db.models.deletion.CASCADE, to='party.address', verbose_name='AddressID')),
                ('ID_PA_PVR_EXTRN', models.ForeignKey(db_column='ID_PA_PVR_EXTRN', on_delete=django.db.models.deletion.CASCADE, to='party.externalpartyidentificationprovider', verbose_name='ExternalPartyIdentificationProviderID')),
                ('ID_PRTY', models.ForeignKey(db_column='ID_PRTY', on_delete=django.db.models.deletion.CASCADE, to='party.party', verbose_name='Party ID')),
                ('ID_PRTY_PRS', models.ForeignKey(db_column='ID_PRTY_PRS', on_delete=django.db.models.deletion.CASCADE, to='party.person', verbose_name='PersonPartyID')),
                ('TY_PRTY_ID', models.ForeignKey(db_column='TY_PRTY_ID', on_delete=django.db.models.deletion.CASCADE, to='party.partyidentificationtype', verbose_name='Party ID')),
            ],
            options={
                'db_table': 'PA_IDTN',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('ID_ORGN', models.BigAutoField(primary_key=True, serialize=False, verbose_name='OrganizationID')),
                ('NM_LGL', models.CharField(max_length=40, verbose_name='LegalName')),
                ('NM_TRD', models.CharField(max_length=40, verbose_name='TradeName')),
                ('DC_TRMN', models.DateTimeField(verbose_name='TerminationDate')),
                ('NM_JRDT_OF_INCRP', models.CharField(max_length=255, verbose_name='JurisdictionOfIncorporation')),
                ('DC_INCRP', models.DateTimeField(verbose_name='IncorporationDate')),
                ('DC_FSC_YR_END', models.DateTimeField(verbose_name='FiscalYearEndDate')),
                ('MO_LCL_ANN_RVN', models.DecimalField(decimal_places=5, max_digits=16, verbose_name='LocalAnnualRevenueAmount')),
                ('MO_GBL_ANN_RVN', models.DecimalField(decimal_places=5, max_digits=16, verbose_name='GlobalAnnualRevenueAmount')),
                ('DC_OPN_FR_BSN', models.DateTimeField(verbose_name='OpenForBusinessDate')),
                ('DC_CLSD_FR_BSN', models.DateTimeField(verbose_name='ClosedForBusinessDate')),
                ('ID_DUNS_NBR', models.CharField(max_length=9, unique=True, verbose_name='DUNSNumber')),
                ('FL_BNKRPTY', models.BooleanField(default=False, verbose_name='BankruptcyFlag')),
                ('DC_BNKRPTY', models.DateTimeField(verbose_name='BankruptcyDate')),
                ('DC_BNKRPTY_EMRGNC', models.DateTimeField(verbose_name='BankruptcyEmergenceDate')),
                ('CD_BNKRPTY_TYP', models.CharField(max_length=20, verbose_name='BankruptcyTypeCode')),
                ('QU_EM_CNT_LCL', models.IntegerField(verbose_name='EmployeeCountLocal')),
                ('QU_EM_CNT_GBL', models.IntegerField(verbose_name='EmployeeCountGlobal')),
                ('CD_RTG_DUNN_AND_BRDST', models.CharField(max_length=20, verbose_name='DunnAndBradstreetRating')),
                ('NA_DE_ORGN', models.TextField(verbose_name='OrganizationDescriptionNarrative')),
                ('CD_LGL_ORGN_TYP', models.ForeignKey(db_column='CD_LGL_ORGN_TYP', on_delete=django.db.models.deletion.CASCADE, to='party.legalorganizationtype', verbose_name='LegalOrganizationTypeCode')),
                ('ID_LGE_PRMRY', models.ForeignKey(db_column='ID_LGE_PRMRY', on_delete=django.db.models.deletion.CASCADE, to='party.language', verbose_name='PrimaryBusinessLanguage')),
                ('ID_PRTY', models.ForeignKey(db_column='ID_PRTY', on_delete=django.db.models.deletion.CASCADE, to='party.party', verbose_name='Party ID')),
            ],
            options={
                'db_table': 'PA_ORGN',
            },
        ),
    ]
