# Generated by Django 4.0.4 on 2022-06-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_externalpartyidentificationprovider_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iso3166_1country',
            options={'verbose_name': 'ISO3166_1Country', 'verbose_name_plural': 'ISO3166_1Countries'},
        ),
        migrations.AlterModelOptions(
            name='iso3166_2countrysubdivision',
            options={'verbose_name': 'ISO3166_2CountrySubdivision'},
        ),
        migrations.AlterModelOptions(
            name='iso3166_2primarysubdivisiontype',
            options={'verbose_name': 'ISO3166_2PrimarySubdivisionType'},
        ),
        migrations.AlterModelOptions(
            name='itucountry',
            options={'verbose_name': 'ITUCountry', 'verbose_name_plural': 'ITUCountries'},
        ),
        migrations.AlterField(
            model_name='contactpurposetype',
            name='CD_TYP_CNCT_PRPS',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ContactPurpose Type Code'),
        ),
    ]
