# Generated by Django 4.0.4 on 2022-07-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_legalorganizationtype_createdby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='CD_LGL_ORGN_TYP',
        ),
    ]
