name                    = "vpc"
cidr                    = "10.1.0.0/16"
public_subnets          = ["10.1.1.0/24", "10.1.2.0/24"]
private_subnets         = ["10.1.3.0/24", "10.1.4.0/24"]
azs                     = ["us-east-2a", "us-east-2b"]
instance_class          = "db.t3.xlarge"
username                = "postgres"
password                = "V9p8h2FvgREhNezQyr"
es_instance_count       = "2"
region                  = "us-east-2"
tenant                  = "dbsupply"
namespace               = "dev"
