# Generated by Django 4.0.4 on 2022-06-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateFormat',
            fields=[
                ('ID_BA_DFMT', models.BigAutoField(primary_key=True, serialize=False, verbose_name='DateFormatID')),
                ('name', models.CharField(max_length=50, verbose_name='Date Format')),
                ('createdby', models.IntegerField(null=True, verbose_name='Created By')),
                ('createddate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updatedby', models.IntegerField(null=True, verbose_name='Updated By')),
                ('updateddate', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Date')),
            ],
            options={
                'db_table': 'CO_BA_DFMT',
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('ID_BA_TZN', models.BigAutoField(primary_key=True, serialize=False, verbose_name='TimezoneID')),
                ('gmt_offset', models.CharField(max_length=100, verbose_name='GMT Offset')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('timezone', models.CharField(max_length=100, verbose_name='Timezone')),
                ('code', models.CharField(max_length=100, verbose_name='Timezone Code')),
                ('createdby', models.IntegerField(null=True, verbose_name='Created By')),
                ('createddate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updatedby', models.IntegerField(null=True, verbose_name='Updated By')),
                ('updateddate', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Date')),
            ],
            options={
                'db_table': 'CO_BA_TZN',
            },
        ),
    ]
