# Generated by Django 4.0.4 on 2022-07-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessunitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Business unit Type', max_length=255, unique=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive')], help_text='Businessunit status (Active/Inactive)', max_length=100, null=True)),
                ('createdby', models.IntegerField(help_text='Created By', null=True)),
                ('createddate', models.DateTimeField(auto_now_add=True, help_text='Date Created', null=True)),
                ('updatedby', models.IntegerField(help_text='Updated By ', null=True)),
                ('updateddate', models.DateTimeField(auto_now=True, help_text='Last Updated Date', null=True)),
            ],
            options={
                'db_table': 'LO_BSN_UN_TY',
            },
        ),
    ]
