# Generated by Django 4.0.4 on 2022-07-18 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_businessunittype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFormField',
            fields=[
                ('ID_BA_CFF', models.BigAutoField(primary_key=True, serialize=False, verbose_name='CustomFormField ID')),
                ('customformfield_name', models.CharField(help_text='Custom form field Name', max_length=40, unique=True, verbose_name='Custom form field Name')),
                ('customformfield_description', models.TextField(blank=True, help_text='Custom form field Description', null=True, verbose_name='Custom form field Description')),
                ('isfilterable', models.BooleanField(blank=True, default=False, help_text='Field is filterable?', null=True, verbose_name='Field is filterable?')),
                ('customformfield_label', models.CharField(blank=True, help_text='Custom form field Label', max_length=255, null=True, verbose_name='Custom form field Label')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2, verbose_name='Status Code')),
                ('isdeleted', models.BooleanField(blank=True, default=False, help_text='Is Deleted?', null=True, verbose_name='isdeleted')),
                ('createdby', models.IntegerField(null=True, verbose_name='Created By')),
                ('createddate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updatedby', models.IntegerField(null=True, verbose_name='Updated By')),
                ('updateddate', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Date')),
            ],
            options={
                'db_table': 'CO_BA_CFF',
            },
        ),
        migrations.CreateModel(
            name='CustomFormFieldType',
            fields=[
                ('ID_BA_CFF_TYP', models.BigAutoField(primary_key=True, serialize=False, verbose_name='CustomFormFieldType ID')),
                ('customformfieldtype_name', models.CharField(help_text='Custom form field Type Name', max_length=255, unique=True, verbose_name='Custom form field Type Name')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2, verbose_name='Status Code')),
                ('isdeleted', models.BooleanField(blank=True, default=False, help_text='Is Deleted?', null=True, verbose_name='isdeleted')),
                ('createdby', models.IntegerField(null=True, verbose_name='Created By')),
                ('createddate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('updatedby', models.IntegerField(null=True, verbose_name='Updated By')),
                ('updateddate', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Date')),
            ],
            options={
                'db_table': 'CO_BA_CFF_TYP',
            },
        ),
        migrations.CreateModel(
            name='CustomFormFieldValue',
            fields=[
                ('ID_BA_CFF_VAL', models.BigAutoField(primary_key=True, serialize=False, verbose_name='CustomFormFieldValue ID')),
                ('customformfield_value', models.CharField(blank=True, help_text='Custom form field Value', max_length=255, verbose_name='Custom form field Value')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2, verbose_name='Status Code')),
                ('isdefault', models.BooleanField(blank=True, default=False, help_text='Is it default?', null=True, verbose_name='isdefault')),
                ('isdeleted', models.BooleanField(blank=True, default=False, help_text='Is Deleted?', null=True, verbose_name='isdeleted')),
                ('ID_BA_CFF', models.ForeignKey(db_column='ID_BA_CFF', help_text='Custom form field Id', on_delete=django.db.models.deletion.CASCADE, to='basics.customformfield', verbose_name='Custom form field Id')),
            ],
            options={
                'db_table': 'CO_BA_CFF_VAL',
            },
        ),
        migrations.AddField(
            model_name='customformfield',
            name='ID_BA_CFF_TYP',
            field=models.ForeignKey(db_column='ID_BA_CFF_TYP', help_text='Custom form field Type Id', on_delete=django.db.models.deletion.PROTECT, to='basics.customformfieldtype', verbose_name='Custom form field Type Id'),
        ),
    ]
