# Generated by Django 4.0.4 on 2022-07-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_customformfield_customformfieldtype_and_more'),
        ('basics', '0003_imageinformation'),
    ]

    operations = [
    ]
