# Generated by Django 4.0.4 on 2022-06-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
