# Generated by Django 4.0.4 on 2022-07-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('I', 'I')], default='A', help_text='Department status (Active/Inactive)', max_length=100, null=True),
        ),
    ]
