# Generated by Django 4.0.4 on 2022-06-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depositrule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTenderRestrictionGroup',
            fields=[
                ('LU_GP_TND_RST', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ItemTenderRestrictionGroupCode')),
                ('DE_GP_TND_RST', models.CharField(max_length=255, verbose_name='Description')),
                ('NA_GP_TND_RST', models.CharField(max_length=40, verbose_name='Name')),
            ],
            options={
                'db_table': 'CO_RST_ITM_TND',
            },
        ),
        migrations.CreateModel(
            name='ItemSellingRule',
            fields=[
                ('ID_RU_ITM_SL', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ItemSellingRuleID')),
                ('SC_ITM_SLS', models.CharField(max_length=2, verbose_name='Status Code')),
                ('DC_ITM_SLS', models.DateTimeField(verbose_name='SellingStatusCodeEffectiveDate')),
                ('FL_CPN_RST', models.IntegerField(verbose_name='CouponRestrictedFlag')),
                ('FL_CPN_ELTNC', models.IntegerField(verbose_name='ElectronicCouponFlag')),
                ('FL_ENR_PRC_RQ', models.IntegerField(verbose_name='PriceEntryRequiredFlag')),
                ('FL_ENT_WT_RQ', models.IntegerField(verbose_name='WeightEntryRequiredFlag')),
                ('FL_DSC_EM_ALW', models.IntegerField(verbose_name='EmployeeDiscountAllowedFlag')),
                ('FL_FD_STP_ALW', models.IntegerField(verbose_name='AllowFoodStampFlag')),
                ('FL_CPN_ALW_MULTY', models.IntegerField(verbose_name='AllowCouponMultiplyFlag')),
                ('QU_MNM_SLS_UN', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='MinimumSaleUnitCount')),
                ('QU_UN_BLK_MXM', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='MaximumSaleUnitCount')),
                ('FL_KY_PRH_RPT', models.IntegerField(verbose_name='ProhibitRepeatKeyFlag')),
                ('FL_PRC_VS_VR', models.IntegerField(verbose_name='VisualVerifyPriceFlag')),
                ('FL_PNT_FQ_SHPR', models.IntegerField(verbose_name='FrequentShopperPointsEligibilityFlag')),
                ('QU_PNT_FQ_SHPR', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='FrequentShopperPointsCount')),
                ('CD_QTY_ACTN_KY', models.CharField(max_length=2, verbose_name='QuantityKeyActionCode')),
                ('FL_RTN_PRH', models.IntegerField(verbose_name='ProhibitReturnFlag')),
                ('FL_ITM_WIC', models.IntegerField(verbose_name='WICFlag')),
                ('FL_ITM_GWY', models.IntegerField(verbose_name='GiveawayFlag')),
                ('FL_RNCHK_EL', models.IntegerField(verbose_name='RaincheckEligibleFlag')),
                ('FL_PRPPRTNL_RFD_EL', models.IntegerField(verbose_name='ProportionalRefundEligibleFlag')),
                ('ID_RU_DS', models.ForeignKey(db_column='ID_RU_DS', on_delete=django.db.models.deletion.CASCADE, to='depositrule.depositrule', verbose_name='DepositRuleID ')),
                ('LU_GP_TND_RST', models.ForeignKey(db_column='LU_GP_TND_RST', on_delete=django.db.models.deletion.CASCADE, to='sellingrule.itemtenderrestrictiongroup', verbose_name='ItemTenderRestrictionGroupCode')),
            ],
            options={
                'db_table': 'RU_ITM_SL',
            },
        ),
    ]
