# Generated by Django 4.0.4 on 2022-07-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellingrule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtenderrestrictiongroup',
            old_name='DE_GP_TND_RST',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='itemtenderrestrictiongroup',
            old_name='NA_GP_TND_RST',
            new_name='name',
        ),
    ]
