# Generated by Django 4.0.4 on 2022-07-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingrule', '0003_rename_id_ru_ds_itemsellingrule_deposit_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsellingrule',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2, verbose_name='Status Code'),
        ),
    ]
