# Generated by Django 4.0.4 on 2022-07-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depositrule', '0005_rename_mo_ds_depositrule_deposit_amount_and_more'),
        ('sellingrule', '0004_alter_itemsellingrule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsellingrule',
            name='deposit_rule',
            field=models.ForeignKey(db_column='ID_RU_DS', null=True, on_delete=django.db.models.deletion.CASCADE, to='depositrule.depositrule', verbose_name='DepositRuleID '),
        ),
    ]
