# Generated by Django 4.0.4 on 2022-07-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellingrule', '0005_alter_itemsellingrule_deposit_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsellingrule',
            name='item_tender_group',
            field=models.ForeignKey(db_column='LU_GP_TND_RST', null=True, on_delete=django.db.models.deletion.CASCADE, to='sellingrule.itemtenderrestrictiongroup', verbose_name='ItemTenderRestrictionGroupCode'),
        ),
    ]
