# Generated by Django 4.0.4 on 2022-07-11 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingrule', '0007_alter_itemsellingrule_deposit_rule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsellingrule',
            old_name='electronic_coupon',
            new_name='FL_CPN_ELTNC',
        ),
        migrations.RenameField(
            model_name='itemsellingrule',
            old_name='coupon',
            new_name='FL_CPN_RST',
        ),
        migrations.RenameField(
            model_name='itemsellingrule',
            old_name='price_entry',
            new_name='FL_ENR_PRC_RQ',
        ),
        migrations.RenameField(
            model_name='itemsellingrule',
            old_name='weight_entry',
            new_name='FL_ENT_WT_RQ',
        ),
        migrations.RenameField(
            model_name='itemsellingrule',
            old_name='deposit_rule',
            new_name='ID_RU_DS',
        ),
        migrations.RenameField(
            model_name='itemsellingrule',
            old_name='item_tender_group',
            new_name='LU_GP_TND_RST',
        ),
        migrations.RenameField(
            model_name='itemtenderrestrictiongroup',
            old_name='selling_rule_description',
            new_name='DE_GP_TND_RST',
        ),
        migrations.RenameField(
            model_name='itemtenderrestrictiongroup',
            old_name='selling_rule_name',
            new_name='NA_GP_TND_RST',
        ),
        migrations.RemoveField(
            model_name='itemsellingrule',
            name='maximum_sale_unit',
        ),
        migrations.RemoveField(
            model_name='itemsellingrule',
            name='minimum_sale_unit',
        ),
        migrations.RemoveField(
            model_name='itemsellingrule',
            name='selling_status_effective_date',
        ),
        migrations.RemoveField(
            model_name='itemsellingrule',
            name='selling_status_expire_date',
        ),
        migrations.AddField(
            model_name='itemsellingrule',
            name='DC_ITM_SLS',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='SellingStatusCodeEffectiveDate'),
        ),
        migrations.AddField(
            model_name='itemsellingrule',
            name='QU_MNM_SLS_UN',
            field=models.DecimalField(decimal_places=0, default=2, max_digits=3, verbose_name='MinimumSaleUnitCount'),
        ),
        migrations.AddField(
            model_name='itemsellingrule',
            name='QU_UN_BLK_MXM',
            field=models.DecimalField(decimal_places=0, default=2, max_digits=3, verbose_name='MaximumSaleUnitCount'),
        ),
        migrations.AddField(
            model_name='itemsellingrule',
            name='SC_ITM_SLS',
            field=models.CharField(default='', max_length=2, verbose_name='Status Code'),
        ),
        migrations.AddField(
            model_name='itemsellingrule',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Expired Date'),
        ),
        migrations.AlterField(
            model_name='itemsellingrule',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2),
        ),
        migrations.AlterModelTable(
            name='itemsellingrule',
            table='ID_RU_ITM_SL',
        ),
    ]
