# Generated by Django 4.0.4 on 2022-07-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellingrule', '0008_rename_electronic_coupon_itemsellingrule_fl_cpn_eltnc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsellingrule',
            name='LU_GP_TND_RST',
        ),
        migrations.AddField(
            model_name='itemsellingrule',
            name='DE_RU_ITM_SL',
            field=models.CharField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='itemsellingrule',
            name='NM_RU_ITM_SL',
            field=models.CharField(max_length=40, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='itemsellingrule',
            name='createdby',
            field=models.IntegerField(null=True, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='itemsellingrule',
            name='createddate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='itemsellingrule',
            name='updatedby',
            field=models.IntegerField(null=True, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='itemsellingrule',
            name='updateddate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated Date'),
        ),
    ]
